# Generated by Django 5.1.6 on 2025-02-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the problem', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(help_text='Full problem statement with details and examples')),
                ('input_format', models.TextField(blank=True, help_text='Description of the input format', null=True)),
                ('output_format', models.TextField(blank=True, help_text='Description of the output format', null=True)),
                ('constraints', models.TextField(blank=True, help_text='Constraints for the problem (if any)', null=True)),
                ('sample_input', models.TextField(blank=True, help_text='A sample input for the problem', null=True)),
                ('sample_output', models.TextField(blank=True, help_text='The expected output for the sample input', null=True)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
