# Generated by Django 5.1.6 on 2025-02-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_submission_verdict_submission_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='sample_input',
            field=models.JSONField(blank=True, help_text='A sample input for the problem in JSON format', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='sample_output',
            field=models.JSONField(blank=True, help_text='The expected output for the sample input in JSON format', null=True),
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
