# Generated by Django 5.1.6 on 2025-02-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hints',
            field=models.TextField(blank=True, help_text='Hints for solving the problem', null=True),
        ),
    ]
